export const environment = {
  production: true,
 // url: "https://api.Real876-App.io",
  url: "https://api.real876.com/",
  
  key_as: 'NTIwQDUyMUA1MjJANTIzQDUyNEA1MjVANTI2QDUyN0A1MjhANTI5QDUzMEA1MzFANTMyQDUzM0A1MzRANTM1QDUzNkA1MzdANTM4QDUzOUA1NDBANTQxQDU0MkA1NDNANTQ0QDU0NUA1NDZANTQ3QDU0OEA1NDlANTUwQDU1MQ==',
  key_vec: 'NTFANTJANTNANTRANTVANTZANTdANThANTlANjBANjFANjJANjNANjRANjVANjY=',
};
